# Generated by Django 6.0.2 on 2026-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
