# Generated by Django 6.0.2 on 2026-02-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tasks_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("wk", "Работа"), ("ln", "Учеба"), ("hm", "Дом")],
                        default="wk",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tasks",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.category",
            ),
        ),
    ]
