# Generated by Django 6.0.2 on 2026-02-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_category_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tasks",
            new_name="Task",
        ),
    ]
