# Generated by Django 6.0.2 on 2026-02-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_tasks_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[("wk", "Работа"), ("ln", "Учеба"), ("hm", "Дом")],
                default="Дом",
                max_length=2,
            ),
        ),
    ]
